name: ItemIncinerator
version: 1.0
main: io.github.zoranac.itemincinerator.ItemIncinerator
api-version: 1.13
commands:
  incinerate:
    description: Destroy items on the ground [distance] blocks away from you.
    usage: /<command> [distance] [item name]
permissions:
  itemincinerator.use:
    description: Allows players to destroy items on the ground [distance] blocks away from you.